name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup .NET 10 RC1
        run: |
          curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 10.0 --install-dir $HOME/.dotnet
          echo "$HOME/.dotnet" >> $GITHUB_PATH
          echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV

      - name: Verify .NET Version
        run: dotnet --version

      - name: Restore Dependencies
        run: dotnet restore app

      # ✅ Update BuildNumber in appsettings.json
      - name: Update Build Number
        run: |
          BUILD_NUMBER="2.0.${{ github.run_number }}"
          echo "Updating BuildNumber to $BUILD_NUMBER"
          jq --arg bn "$BUILD_NUMBER" '.BuildNumber = $bn' app/wwwroot/appsettings.json > temp.json && mv temp.json app/wwwroot/appsettings.json

      - name: Build Blazor WebAssembly
        run: dotnet build app --configuration Release --no-restore

      # ✅ Publish with compression enabled
      - name: Publish Blazor WebAssembly (with compression)
        run: dotnet publish app/app.csproj -c Release -- /p:BlazorWebAssemblyEnableAOT=false /p:CompressionEnabled=true

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "app/build/wwwroot"
          api_location: ""
          output_location: ""

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"





